src_dir: "/template_dir"
template:
  flask:
    directory: "flask"
    description: "Python basic files to work with Flask"
    gitignore:
      - "__pycache__/"
  typescript:
    directory: "typescript"
    description: "Typescript basic files, with strict configuration in JavaScript es2016"
    gitignore:
     - "/dist"
  python:
    directory : "python-main"
    description : "Python basic project files"
    gitignore:
      - "venv/"

